### ISSUE TITLE
Krastorio 2 

### ISSUE THREAD

**Issue by Ectalite** [HySpeed/CitiesOfEarth3#16]
Hi,

When playing with Krastorio 2, creep should spawn near of spawners, but when using CitiesOfEarth3 generation it doesn't.
It's a pretty big issue as creep is used in military research and therefore it locks the progression.

**Comment by HySpeed** [comment]
Hi, 
I know that it does spawn as I am doing a play-through of K2 on CoE3 (~200 hours in). (twitch.tv/hy_speed)
There was an older version of CoE3 that didn't support creep, but I added that CoE3 v1.7.2.
So please ensure you are using at least that version and have Krastorio 2 correctly installed (including the required mods).

Let me know if this problem continues.

thanks

**Comment by Ectalite** [comment]
I have CoE3 v.1.7.9 and Krastorio v1.3.22 installed.
I tried creating maps with and without CoE3 (I did not touch other mods) and creep wasn't spawning when CoE3 was enabled.

In the scenario editor, I created a new map.
On Earth Bitter's Spawners are generated like that:
![image](https://github.com/HySpeed/CitiesOfEarth3/assets/31344054/cfb79cb8-aa9e-4259-89ce-8ace630c8cf6)
And on Nauvis they are generated like this:
![image](https://github.com/HySpeed/CitiesOfEarth3/assets/31344054/cc9ad706-72b4-4585-b846-377684029048)

**Comment by Ectalite** [comment]
After trying v1.7.2 specificaly it was not better, so I reupdated CoE3 to 1.7.9.
I don't know why, but this time creep is generated, but a lot less than on nauvis.

With the default settings:
On nauvis, each Bitter's Camp has a lot of creep. On earth, some don't have creep, and other just have a bit near of them.

**Comment by HySpeed** [comment]
good that it works at least.  My mod just makes a remote call to enable creep in the Krastorio 2.  I don't know what it does internally.
