### ISSUE TITLE
Crashes when loading saved game

### ISSUE THREAD

**Issue by edvardm** [HySpeed/CitiesOfEarth3#17]
Game consistently crashed upon loading a saved game with SO. Admittedly there were few extra mods related to train coupling, but removing those didn't seem to help so what I did in the end opened the throwing function and replaced `createForces` in `coe_worldgen.lua` with

```lua
local function createForces( world )
  for _, city in pairs( world.cities ) do
    if pcall(game.create_force, city.name) then
      -- ugly hack to wrap create_force() in `pcall()` to avoid obscure "force already exists" error
      game.forces[city.name].set_spawn_position( city.position, world.surface )
    end
  end
end
```

not pretty, but did it for us, save loaded fine and we could go on (don't know lua nor how mod actually works). Thanks for the great mod! Playing with actual map is oddly satisfying

**Comment by HySpeed** [comment]
Hi,
Thanks for the info.  Do you have the save that crashed?  I'd like to debug it and improve the mod.
thanks
    On Saturday, March 9, 2024 at 11:32:16 AM EST, Edvard Majakari ***@***.***> wrote:  
 
 


Game consistently crashed upon loading a saved game with SO. Admittedly there were few extra mods related to train coupling, but removing those didn't seem to help so what I did in the end opened the throwing function and replaced createForces in coe_worldgen.lua with
local function createForces( world )
  for _, city in pairs( world.cities ) do
    if pcall(game.create_force, city.name) then
      -- ugly hack to wrap create_force() in `pcall()` to avoid obscure "force already exists" error
      game.forces[city.name].set_spawn_position( city.position, world.surface )
    end
  end
end
not pretty, but did it for us, save loaded fine and we could go on. Thanks for the great mod! Playing with actual map is oddly satisfying

**Comment by edvardm** [comment]
> Hi, Thanks for the info.  Do you have the save that crashed?  I'd like to debug it and improve the mod. thanks

Sure, just checked whether the save file has still the same issue. Note that I still worry it might be due to some mod, not sure -- tried to remove some of them but didn't try removing all. 

Save file should be accessible from https://drive.google.com/file/d/11lW4n_ZvbdZe8eltUn74owI0dzKOuD2Z/view?usp=sharing

**Comment by HySpeed** [comment]
I (finally) fixed this.  thanks for letting me know about it.
